project:
  type: website
  output-dir: docs  

website:
  title: "Indicator Reference"
  sidebar:
    style: "docked"
    contents:
      - text: 'Blight violations'
        href: 'Detroit Blight Violations Analysis (2022-2024).qmd'
      - text: Redlining  
        href: HRI-Mapping-Detroit-2020-Census-Tracts.qmd
        
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true